### ISSUE TITLE
Crash after upgrading for python 3.5

### ISSUE THREAD

**Issue by kkalera** [PhilippeMorere/BasicReinforcementLearning#2]
Hi,

I'm using python 3.5.2, so I needed to make a few changes to the World.py file.

on line 2 I changed `from Tkinter import *` to  `from tkinter import *`
Then on line 92 and 94 I put `()` around the print commands:
changing `print "Success! score: ", score` into `print ("Success! score: ", score)`
and `print "Fail! score: ", score` into `print ("Fail! score: ", score)`

Now when I run the QLearner.py, I'm getting the following error:
`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/kalera/anaconda3/envs/universe/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/kalera/anaconda3/envs/universe/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "Learner.py", line 74, in run
    inc_Q(s, a, alpha, r + discount * max_val)
  File "Learner.py", line 58, in inc_Q
    World.set_cell_score(s, a, Q[s][a])
  File "/home/kalera/PycharmProjects/q_learning_demo/World.py", line 74, in set_cell_score
    board.itemconfigure(triangle, fill=color)
  File "/home/kalera/anaconda3/envs/universe/lib/python3.5/tkinter/__init__.py", line 2427, in itemconfigure
    return self._configure(('itemconfigure', tagOrId), cnf, kw)
  File "/home/kalera/anaconda3/envs/universe/lib/python3.5/tkinter/__init__.py", line 1330, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: out of stack space (infinite loop?)
`

**Comment by PhilippeMorere** [comment]
Hi,
Porting code from python2 to python3 can be more complicated than just changing print statements and library calls.
From your error, it seems that the code in World.py handling rendering is not adapted to Tkinter for python3. You would have to look at API changes in Tkinter from python 2 to 3.
If you get this to work, please send a pull request, as I would happily port this project to python3.

**Comment by kkalera** [comment]
Hi @PhilippeMorere 
I'll take a look at it! I'm new to python, so I was not aware that porting from 2 to 3 was more complex. 
Thank you for your explanation!
